# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 609676f9d745584d041a846bd6dc7281e7542294db53fb20681f7e87963a801a5e68196ffcf7e578dc94ac06d938fbf4cac32bda931d7c0e483e00b2e966594e

test:
  secret_key_base: 50d573119e91d47ef616860d9cb80a25dac56479d3ba7ade15fd9272ea65b33ce5d86c09122d5edb1690d470ad175aff9e57871a74c54ed8741276ba6ee8097c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
